# Generated by Django 5.1.1 on 2024-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='Area_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='Player_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='Team_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='area',
            new_name='team_area',
        ),
    ]
