# Generated by Django 5.1.1 on 2024-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_rename_name_area_area_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_area',
            field=models.CharField(max_length=100),
        ),
    ]
