# Generated by Django 5.1.1 on 2024-09-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_team_team_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.area'),
        ),
    ]
