# Generated by Django 5.1.1 on 2024-09-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_team_team_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Area_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team_name',
            new_name='name',
        ),
    ]
