# Generated by Django 5.1.1 on 2024-09-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_rename_area_name_area_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='teamname',
        ),
    ]
