# Generated by Django 5.1.1 on 2024-09-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_rename_name_team_teamname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='Playername',
        ),
    ]
