# Generated by Django 5.1.1 on 2024-09-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_rename_name_player_playername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='areaname',
        ),
    ]
