# Generated by Django 5.1.1 on 2024-09-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_rename_name_area_areaname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score_away',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_home',
        ),
    ]
